# ==============================================================================
# SSLPROXY GLOBAL CONFIGURATION
# ==============================================================================
CACert /etc/sslproxy/utmca.crt
CAKey /etc/sslproxy/utmca.key
PidFile /var/run/sslproxy.pid
LeafKey /etc/sslproxy/leaf.key
ECDHCurve prime256v1

WriteGenCertsDir /var/log/sslproxy/cert_cache

MirrorIf tzsp0
Daemon no
Debug no
DebugLevel 2

ConnIdleTimeout 120
ExpiredConnCheckPeriod 30
LogStats no
StatsPeriod 10

RemoveHTTPAcceptEncoding no
RemoveHTTPReferer no
VerifyPeer yes
AllowWrongHost no
StripClientHello no
Passthrough yes

MaxSSLProto tls13
#MinSSLProto tls10
DenyOCSP yes

OpenFilesLimit 10000

# ==============================================================================
# STRUCTURED PROXYSPECS
# ==============================================================================

ProxySpec {
    Proto https
    Addr ::
    Port 8443
    SNIPort 443
    Divert no
}

ProxySpec {
    Proto pop3s
    Addr ::
    Port 8995
    NatEngine netfilter
    Divert no
}

ProxySpec {
    Proto smtps
    Addr ::
    Port 8465
    NatEngine netfilter
    Divert no
}

ProxySpec {
    Proto http
    Addr ::
    Port 8081
    NatEngine netfilter
    Divert no
}
